### PR TITLE
Add v6 tests

### PR DESCRIPTION
**Pull request by timwis**
Replaces #528. I was just going off the features listed in the readme. There are a handful more we should test but this is a start.

Note that this includes a readme change for `state.href` that I believe was incorrectly documented. Let me know if I got that wrong.

Also note that we should delete the original `v6-tests` branch once this is merged. Leaving it for now for reference.

### CODE REVIEW

**Comment by tornqvist** [comment]
I've added tests for the new component cache. Would it be alright if I push them to this branch?

**Comment by bcomnes** [comment]
Up to Tim, but I'm cool with it.  We should land these.

**Comment by timwis** [comment]
Absolutely!

**Comment by bcomnes** [comment]
🎉

**Pull request merged**
