### PR TITLE
exporting bel/raw via choo/html/raw

### PR DESCRIPTION
**Pull request by graforlock**
- Created html folder
- Default `require('choo/html')` looks for html/index.js
- Specific `require('choo/html/raw')` will now get `bel/raw`module at html/raw.js
- `test.js` updated
- `package.json` updated

as per [#562](https://github.com/choojs/choo/issues/562)

### CODE REVIEW

**Comment by graforlock** [comment]
Just found i commited package-lock which wasn't there! Its not in .gitignore either, whats the course of action, opinion on the lock?

**Comment by graforlock** [comment]
Anyone alive here?

**Comment by bcomnes** [comment]
Added you as a contributor to get some more bandwidth here.

**Comment by bcomnes** [comment]
@graforlock we can release this as semver minor.  Feel free to hop on irc for more realtime discussions at any point.

**Pull request merged**
