### PR TITLE
State in tostring

### PR DESCRIPTION
**Pull request by yoshuawuyts**
Found a few bugs with server rendering.
- `state.title` wasn't being set on first render
- `state.events` wasn't being set when rendering on server.

Thanks!

### CODE REVIEW

**Comment by yoshuawuyts** [comment]
cc/ @choojs/trainspotters review welcome!

**Comment by lrlna** [comment]
omg. yosh. that group name.

**Comment by toddself** [comment]
`toString` is only used on the server end right?  Is that API available in the client? (Should it be used in the client)?  Should we tell browserify to not include xtend in the bundle?

Then again xtend is minuscule...

**Comment by yoshuawuyts** [comment]
xtend is already being used by child deps, so it'll only use a single
instance. You're right tho - it shouldn't be used in the client b/c no
useful results will come out of it. Adding an assertion!

**Pull request merged**
