### PR TITLE
add files field into package.json

### LINKED ISSUE #537: make a umd build available for unpkg CDN
Would it be possible to make a [UMD](https://github.com/umdjs/umd) build of choo available on npm? That way it colud be used via [unpkg](unpkg.com) CDN on the likes of codepen, jsfiddle, etc.

### PR DESCRIPTION
**Pull request by tgfjt**
resolve #537

### CODE REVIEW

**Comment by emilbayes** [comment]
Does this mean that `README.md` and `example` don't come with `npm install`? Because that would make me sad 😢

**Comment by tgfjt** [comment]
@emilbayes 
`README` is always included!
https://docs.npmjs.com/files/package.json#files

I'm just curious that how come do you want `example` via `npm install`?

**Comment by toddself** [comment]
This looks good to me.

**Comment by yoshuawuyts** [comment]
`v6.0.0-4`

**Pull request merged**
